// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	v1 "github.com/redish101/depositum/pkg/api/v1"
)

type Libraries struct {
	Items    []*v1.Library `json:"items"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type Mutation struct {
}

type ObjectStatusInput struct {
	Phase     v1.ObjectPhase `json:"phase"`
	LibraryID *uint          `json:"libraryID,omitempty"`
	ShelfID   *uint          `json:"shelfID,omitempty"`
}

type Objects struct {
	Items    []*v1.Object `json:"items"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type PageInfo struct {
	Total   int32 `json:"total"`
	HasNext bool  `json:"HasNext"`
	HasPrev bool  `json:"HasPrev"`
}

type PageParams struct {
	Page     int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
}

type Query struct {
}

type Shelves struct {
	Items    []*v1.Shelf `json:"items"`
	PageInfo *PageInfo   `json:"pageInfo"`
}
