/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */

export type GetObjectsParams = {
  /**
   * 页码
   */
  page?: number
  /**
   * 每页数量
   */
  pageSize?: number
}
