/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */

export interface GithubComRedish101DepositumPkgApiV1CreateLibraryRequest {
  address: string
  name: string
}
