/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComRedish101DepositumPkgApiV1LibrarySummary } from "./githubComRedish101DepositumPkgApiV1LibrarySummary"
import type { GithubComRedish101DepositumPkgApiV1ObjectPhase } from "./githubComRedish101DepositumPkgApiV1ObjectPhase"
import type { GithubComRedish101DepositumPkgApiV1ShelfSummary } from "./githubComRedish101DepositumPkgApiV1ShelfSummary"

export interface GithubComRedish101DepositumPkgApiV1ObjectStatus {
  library?: GithubComRedish101DepositumPkgApiV1LibrarySummary
  phase?: GithubComRedish101DepositumPkgApiV1ObjectPhase
  shelf?: GithubComRedish101DepositumPkgApiV1ShelfSummary
}
