/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */

export type GithubComRedish101DepositumPkgApiV1ObjectPhase =
  (typeof GithubComRedish101DepositumPkgApiV1ObjectPhase)[keyof typeof GithubComRedish101DepositumPkgApiV1ObjectPhase]

export const GithubComRedish101DepositumPkgApiV1ObjectPhase = {
  ObjectPhaseCreated: "CREATED",
  ObjectPhaseArchived: "ARCHIVED",
  ObjectPhaseWithdrawn: "WITHDRAWN",
  ObjectPhaseDeleted: "DELETED",
  ObjectPhaseLost: "LOST",
} as const
