/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComRedish101DepositumPkgApiV1ObjectStatus } from "./githubComRedish101DepositumPkgApiV1ObjectStatus"

export interface GithubComRedish101DepositumPkgApiV1Object {
  createdAt?: string
  currentStatus?: GithubComRedish101DepositumPkgApiV1ObjectStatus
  description?: string
  desiredStatus?: GithubComRedish101DepositumPkgApiV1ObjectStatus
  id?: number
  name?: string
  synced?: boolean
  updatedAt?: string
}
