/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComRedish101DepositumPkgApiV1Shelf } from "./githubComRedish101DepositumPkgApiV1Shelf"

export interface GithubComRedish101DepositumPkgApiV1PaginationResponseGithubComRedish101DepositumPkgApiV1Shelf {
  /** 是否有下一页 */
  hasNext?: boolean
  /** 是否有上一页 */
  hasPrev?: boolean
  /** 数据列表 */
  items?: GithubComRedish101DepositumPkgApiV1Shelf[]
  /** 当前页码 */
  page?: number
  /** 每页大小 */
  pageSize?: number
  /** 总记录数 */
  total?: number
  /** 总页数 */
  totalPages?: number
}
