/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComRedish101DepositumPkgApiV1ObjectPhase } from "./githubComRedish101DepositumPkgApiV1ObjectPhase"

export interface GithubComRedish101DepositumPkgApiV1ObjectStatusInput {
  libraryID?: number
  phase?: GithubComRedish101DepositumPkgApiV1ObjectPhase
  shelfID?: number
}
