/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComRedish101DepositumPkgApiV1LibrarySummary } from "./githubComRedish101DepositumPkgApiV1LibrarySummary"

export interface GithubComRedish101DepositumPkgApiV1Shelf {
  createdAt?: string
  description?: string
  id?: number
  library?: GithubComRedish101DepositumPkgApiV1LibrarySummary
  name?: string
  updatedAt?: string
}
