/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * depositum API
 * 档案管理系统 API
 * OpenAPI spec version: 1.0
 */

export * from "./getLibrariesParams"
export * from "./getObjectsParams"
export * from "./getShelvesParams"
export * from "./githubComRedish101DepositumPkgApiV1CreateLibraryRequest"
export * from "./githubComRedish101DepositumPkgApiV1CreateObjectRequest"
export * from "./githubComRedish101DepositumPkgApiV1CreateShelfRequest"
export * from "./githubComRedish101DepositumPkgApiV1ErrorResponse"
export * from "./githubComRedish101DepositumPkgApiV1Library"
export * from "./githubComRedish101DepositumPkgApiV1LibrarySummary"
export * from "./githubComRedish101DepositumPkgApiV1ListObjectRequest"
export * from "./githubComRedish101DepositumPkgApiV1Object"
export * from "./githubComRedish101DepositumPkgApiV1ObjectPhase"
export * from "./githubComRedish101DepositumPkgApiV1ObjectStatus"
export * from "./githubComRedish101DepositumPkgApiV1ObjectStatusInput"
export * from "./githubComRedish101DepositumPkgApiV1PaginationResponseGithubComRedish101DepositumPkgApiV1Library"
export * from "./githubComRedish101DepositumPkgApiV1PaginationResponseGithubComRedish101DepositumPkgApiV1Object"
export * from "./githubComRedish101DepositumPkgApiV1PaginationResponseGithubComRedish101DepositumPkgApiV1Shelf"
export * from "./githubComRedish101DepositumPkgApiV1Shelf"
export * from "./githubComRedish101DepositumPkgApiV1ShelfSummary"
export * from "./githubComRedish101DepositumPkgApiV1UpdateLibraryRequest"
export * from "./githubComRedish101DepositumPkgApiV1UpdateObjectRequest"
export * from "./githubComRedish101DepositumPkgApiV1UpdateShelfRequest"
