enum ObjectPhase {
    CREATED
    ARCHIVED
    WITHDRAWN
    DELETED
    LOST
}

type ObjectStatus {
    phase: ObjectPhase!
    library: Library
    shelf: Shelf
}

input ObjectStatusInput {
    phase: ObjectPhase!
    libraryID: ID
    shelfID: ID
}

type Object {
    id: ID!
    createdAt: Time!
    updatedAt: Time!

    name: String!
    description: String
    desiredStatus: ObjectStatus!
    currentStatus: ObjectStatus!

    synced: Boolean!
}

type Objects {
    items: [Object!]!
    pageInfo: PageInfo!
}

input ListObjectRequest {
    syncedOnly: Boolean
    unsyncedOnly: Boolean
    libraryID: ID
    shelfID: ID
}

input CreateObjectRequest {
    name: String!
    description: String
    desiredStatus: ObjectStatusInput!
    syncNow: Boolean
}

input UpdateObjectRequest {
    name: String
    description: String
    desiredStatus: ObjectStatusInput
    syncNow: Boolean
}

extend type Query {
    object(id: ID!): Object
    objects(input: ListObjectRequest, pageParams: PageParams): Objects!
}

extend type Mutation {
    createObject(input: CreateObjectRequest!): Object!

    updateObject(
        id: ID!
        input: UpdateObjectRequest!
    ): Object!

    deleteObject(id: ID!): Boolean!
    sync(id: ID!): Object!
}
