type Shelf {
    id: ID!
    createdAt: Time!
    updatedAt: Time!

    name: String!
    description: String
    library: Library!
}

type Shelves {
    items: [Shelf!]!
    pageInfo: PageInfo!
}

input CreateShelfRequest {
    name: String!
    description: String
    libraryID: ID!
}

input UpdateShelfRequest {
    name: String
    description: String
    libraryID: ID
}

extend type Query {
    shelf(id: ID!): Shelf
    shelves(pageParams: PageParams): Shelves!
}

extend type Mutation {
    createShelf(input: CreateShelfRequest!): Shelf!

    updateShelf(
        id: ID!
        input: UpdateShelfRequest!
    ): Shelf!

    deleteShelf(id: ID!): Boolean!
}
