package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	v1 "github.com/redish101/depositum/pkg/api/v1"
	"github.com/redish101/depositum/pkg/graph"
	"github.com/redish101/depositum/pkg/graph/model"
)

// CreateLibrary is the resolver for the createLibrary field.
func (r *mutationResolver) CreateLibrary(ctx context.Context, input v1.CreateLibraryRequest) (*v1.Library, error) {
	library, err := r.libraryService.Create(ctx, &input)
	if err != nil {
		return nil, err
	}
	return library, nil
}

// UpdateLibrary is the resolver for the updateLibrary field.
func (r *mutationResolver) UpdateLibrary(ctx context.Context, id uint, input v1.UpdateLibraryRequest) (*v1.Library, error) {
	library, err := r.libraryService.Update(ctx, id, &input)
	if err != nil {
		return nil, err
	}
	return library, nil
}

// DeleteLibrary is the resolver for the deleteLibrary field.
func (r *mutationResolver) DeleteLibrary(ctx context.Context, id uint) (bool, error) {
	err := r.libraryService.Delete(ctx, id)

	if err != nil {
		return false, err
	}

	return true, nil
}

// Library is the resolver for the library field.
func (r *queryResolver) Library(ctx context.Context, id uint) (*v1.Library, error) {
	library, err := r.libraryService.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	return library, nil
}

// Libraries is the resolver for the libraries field.
func (r *queryResolver) Libraries(ctx context.Context, pageParams *model.PageParams) (*model.Libraries, error) {
	libraries, err := r.libraryService.List(ctx, covertPageParams(pageParams))
	if err != nil {
		return nil, err
	}

	return &model.Libraries{
		Items:    libraries.Items,
		PageInfo: pageInfo(libraries),
	}, err
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
