package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/redish101/depositum/internal/service"
	v1 "github.com/redish101/depositum/pkg/api/v1"
	"github.com/redish101/depositum/pkg/graph"
	"github.com/redish101/depositum/pkg/graph/model"
)

// CreateObject is the resolver for the createObject field.
func (r *mutationResolver) CreateObject(ctx context.Context, input v1.CreateObjectRequest) (*v1.Object, error) {
	return r.objectService.Create(ctx, &input)
}

// UpdateObject is the resolver for the updateObject field.
func (r *mutationResolver) UpdateObject(ctx context.Context, id uint, input v1.UpdateObjectRequest) (*v1.Object, error) {
	return r.objectService.Update(ctx, id, &input)
}

// DeleteObject is the resolver for the deleteObject field.
func (r *mutationResolver) DeleteObject(ctx context.Context, id uint) (bool, error) {
	err := r.objectService.Delete(ctx, id)
	return err == nil, err
}

// Sync is the resolver for the sync field.
func (r *mutationResolver) Sync(ctx context.Context, id uint) (*v1.Object, error) {
	return r.objectService.Sync(ctx, id)
}

// Library is the resolver for the library field.
func (r *objectStatusResolver) Library(ctx context.Context, obj *v1.ObjectStatus) (*v1.Library, error) {
	library, err := r.libraryService.Get(ctx, obj.LibraryID)
	if errors.Is(err, service.ErrLibraryNotFound) {
		return nil, nil
	}
	return library, err
}

// Shelf is the resolver for the shelf field.
func (r *objectStatusResolver) Shelf(ctx context.Context, obj *v1.ObjectStatus) (*v1.Shelf, error) {
	shelf, err := r.shelfService.Get(ctx, obj.ShelfID)
	if errors.Is(err, service.ErrShelfNotFound) {
		return nil, nil
	}
	return shelf, err
}

// Object is the resolver for the object field.
func (r *queryResolver) Object(ctx context.Context, id uint) (*v1.Object, error) {
	return r.objectService.Get(ctx, id)
}

// Objects is the resolver for the objects field.
func (r *queryResolver) Objects(ctx context.Context, input *v1.ListObjectRequest, pageParams *model.PageParams) (*model.Objects, error) {
	objects, err := r.objectService.List(ctx, covertPageParams(pageParams), input)
	return &model.Objects{
		Items:    objects.Items,
		PageInfo: pageInfo(objects),
	}, err
}

// DesiredStatus is the resolver for the desiredStatus field.
func (r *createObjectRequestResolver) DesiredStatus(ctx context.Context, obj *v1.CreateObjectRequest, data *model.ObjectStatusInput) error {
	obj.DesiredStatus = v1.ObjectStatus{
		Phase:     data.Phase,
		LibraryID: *data.LibraryID,
		ShelfID:   *data.ShelfID,
	}

	return nil
}

// DesiredStatus is the resolver for the desiredStatus field.
func (r *updateObjectRequestResolver) DesiredStatus(ctx context.Context, obj *v1.UpdateObjectRequest, data *model.ObjectStatusInput) error {
	obj.DesiredStatus = &v1.ObjectStatus{
		Phase:     data.Phase,
		LibraryID: *data.LibraryID,
		ShelfID:   *data.ShelfID,
	}

	return nil
}

// ObjectStatus returns graph.ObjectStatusResolver implementation.
func (r *Resolver) ObjectStatus() graph.ObjectStatusResolver { return &objectStatusResolver{r} }

// CreateObjectRequest returns graph.CreateObjectRequestResolver implementation.
func (r *Resolver) CreateObjectRequest() graph.CreateObjectRequestResolver {
	return &createObjectRequestResolver{r}
}

// UpdateObjectRequest returns graph.UpdateObjectRequestResolver implementation.
func (r *Resolver) UpdateObjectRequest() graph.UpdateObjectRequestResolver {
	return &updateObjectRequestResolver{r}
}

type (
	objectStatusResolver        struct{ *Resolver }
	createObjectRequestResolver struct{ *Resolver }
	updateObjectRequestResolver struct{ *Resolver }
)
