package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	v1 "github.com/redish101/depositum/pkg/api/v1"
	"github.com/redish101/depositum/pkg/graph"
	"github.com/redish101/depositum/pkg/graph/model"
)

// CreateShelf is the resolver for the createShelf field.
func (r *mutationResolver) CreateShelf(ctx context.Context, input v1.CreateShelfRequest) (*v1.Shelf, error) {
	return r.shelfService.Create(ctx, &input)
}

// UpdateShelf is the resolver for the updateShelf field.
func (r *mutationResolver) UpdateShelf(ctx context.Context, id uint, input v1.UpdateShelfRequest) (*v1.Shelf, error) {
	return r.shelfService.Update(ctx, id, &input)
}

// DeleteShelf is the resolver for the deleteShelf field.
func (r *mutationResolver) DeleteShelf(ctx context.Context, id uint) (bool, error) {
	err := r.shelfService.Delete(ctx, id)
	return err == nil, err
}

// Shelf is the resolver for the shelf field.
func (r *queryResolver) Shelf(ctx context.Context, id uint) (*v1.Shelf, error) {
	return r.shelfService.Get(ctx, id)
}

// Shelves is the resolver for the shelves field.
func (r *queryResolver) Shelves(ctx context.Context, pageParams *model.PageParams) (*model.Shelves, error) {
	shelves, err := r.shelfService.List(ctx, covertPageParams(pageParams))
	return &model.Shelves{
		Items:    shelves.Items,
		PageInfo: pageInfo(shelves),
	}, err
}

// Library is the resolver for the library field.
func (r *shelfResolver) Library(ctx context.Context, obj *v1.Shelf) (*v1.Library, error) {
	return r.libraryService.Get(ctx, obj.LibraryID)
}

// Shelf returns graph.ShelfResolver implementation.
func (r *Resolver) Shelf() graph.ShelfResolver { return &shelfResolver{r} }

type shelfResolver struct{ *Resolver }
